services:
  wordpress_sitehaat:
    image: wordpress:fpm
    container_name: wordpress_sitehaat
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: b2buser
      WORDPRESS_DB_PASSWORD: b2bpass
      WORDPRESS_DB_NAME: wordpress_sitehaat
    volumes:
      - wordpress_sitehaat_data:/var/www/html
    networks:
      - comarto_network

  wordpress_akhlaqfood:
    image: wordpress:fpm
    container_name: wordpress_akhlaqfood
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: b2buser
      WORDPRESS_DB_PASSWORD: b2bpass
      WORDPRESS_DB_NAME: wordpress_akhlaqfood
    volumes:
      - wordpress_akhlaqfood_data:/var/www/html
    networks:
      - comarto_network

  wordpress_grocery:
    image: wordpress:fpm
    container_name: wordpress_grocery
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: b2buser
      WORDPRESS_DB_PASSWORD: b2bpass
      WORDPRESS_DB_NAME: wordpress_grocery
    volumes:
      - wordpress_grocery_data:/var/www/html
    networks:
      - comarto_network

volumes:
  wordpress_sitehaat_data:
  wordpress_akhlaqfood_data:
  wordpress_grocery_data:

networks:
  comarto_network:
    external: true